// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_ji2LfvT7Bwms-9vUldz93qalicE4kZw',
    appId: '1:802309752240:web:f07edaa992daf0f2d18275',
    messagingSenderId: '802309752240',
    projectId: 'ecokids2-4face',
    authDomain: 'ecokids2-4face.firebaseapp.com',
    storageBucket: 'ecokids2-4face.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDC6TXvD7fIRIIj4CVikCc8YjOa594gWQ',
    appId: '1:802309752240:android:9e384b43f30ce5d2d18275',
    messagingSenderId: '802309752240',
    projectId: 'ecokids2-4face',
    storageBucket: 'ecokids2-4face.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBm3MgpI1xfJ4AE6LVL79Sr7tNb4KZDXUk',
    appId: '1:802309752240:ios:560f7f40b17e27a3d18275',
    messagingSenderId: '802309752240',
    projectId: 'ecokids2-4face',
    storageBucket: 'ecokids2-4face.firebasestorage.app',
    iosBundleId: 'com.example.ecokids',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBm3MgpI1xfJ4AE6LVL79Sr7tNb4KZDXUk',
    appId: '1:802309752240:ios:560f7f40b17e27a3d18275',
    messagingSenderId: '802309752240',
    projectId: 'ecokids2-4face',
    storageBucket: 'ecokids2-4face.firebasestorage.app',
    iosBundleId: 'com.example.ecokids',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_ji2LfvT7Bwms-9vUldz93qalicE4kZw',
    appId: '1:802309752240:web:f8f972ce336d238fd18275',
    messagingSenderId: '802309752240',
    projectId: 'ecokids2-4face',
    authDomain: 'ecokids2-4face.firebaseapp.com',
    storageBucket: 'ecokids2-4face.firebasestorage.app',
  );
}
